from machine import Pin 
import utime

red_1 = Pin(0, Pin.OUT)
orange_1 = Pin(1, Pin.OUT)
green_1 = Pin(2, Pin.OUT)
red_2 = Pin(3, Pin.OUT)
orange_2 = Pin(4, Pin.OUT)
green_2 = Pin(5, Pin.OUT)
red_3 = Pin(6, Pin.OUT)
orange_3 = Pin(7, Pin.OUT)
green_3 = Pin(8, Pin.OUT)
red_4 = Pin(9, Pin.OUT)
orange_4 = Pin(10, Pin.OUT)
green_4 = Pin(11, Pin.OUT)

def deirection_1_green():
  red_1.value(0)
  orange_1.value(0)
  green_1.value(1)
  red_2.value(1)
  orange_2.value(0)
  green_2.value(0)
  red_3.value(1)
  orange_3.value(0)
  green_3.value(0)
  red_4.value(1)
  orange_4.value(0)
  green_4.value(0)

def deirection_2_orange():
  red_1.value(1)
  orange_1.value(0)
  green_1.value(0)
  red_2.value(0)
  orange_2.value(1)
  green_2.value(0)
  red_3.value(1)
  orange_3.value(0)
  green_3.value(0)
  red_4.value(1)
  orange_4.value(0)
  green_4.value(0)

def deirection_2_green():
  red_1.value(1)
  orange_1.value(0)
  green_1.value(0)
  red_2.value(0)
  orange_2.value(0)
  green_2.value(1)
  red_3.value(1)
  orange_3.value(0)
  green_3.value(0)
  red_4.value(1)
  orange_4.value(0)
  green_4.value(0)

def deirection_3_orange():
  red_1.value(1)
  orange_1.value(0)
  green_1.value(0)
  red_2.value(1)
  orange_2.value(0)
  green_2.value(0)
  red_3.value(0)
  orange_3.value(1)
  green_3.value(0)
  red_4.value(1)
  orange_4.value(0)
  green_4.value(0)

def deirection_3_green():
  red_1.value(1)
  orange_1.value(0)
  green_1.value(0)
  red_2.value(1)
  orange_2.value(0)
  green_2.value(0)
  red_3.value(0)
  orange_3.value(0)
  green_3.value(1)
  red_4.value(1)
  orange_4.value(0)
  green_4.value(0)

def deirection_4_orange():
  red_1.value(1)
  orange_1.value(0)
  green_1.value(0)
  red_2.value(1)
  orange_2.value(0)
  green_2.value(0)
  red_3.value(1)
  orange_3.value(0)
  green_3.value(0)
  red_4.value(0)
  orange_4.value(1)
  green_4.value(0)

def deirection_4_green():
  red_1.value(1)
  orange_1.value(0)
  green_1.value(0)
  red_2.value(1)
  orange_2.value(0)
  green_2.value(0)
  red_3.value(1)
  orange_3.value(0)
  green_3.value(0)
  red_4.value(0)
  orange_4.value(0)
  green_4.value(1)

def deirection_1_orange():
  red_1.value(0)
  orange_1.value(1)
  green_1.value(0)
  red_2.value(1)
  orange_2.value(0)
  green_2.value(0)
  red_3.value(1)
  orange_3.value(0)
  green_3.value(0)
  red_4.value(1)
  orange_4.value(0)
  green_4.value(0)

while True:
  deirection_1_green()
  utime.sleep(5)
  deirection_1_orange()
  utime.sleep(2)
  deirection_2_green()
  utime.sleep(5)
  deirection_2_orange()
  utime.sleep(2)
  deirection_3_green()
  utime.sleep(5)
  deirection_3_orange()
  utime.sleep(2)
  deirection_4_green()
  utime.sleep(5)
  deirection_4_orange()
  utime.sleep(2)

